### ISSUE TITLE
Kollegschaft is not recognized by Language Tool

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#237]
## Is situation

<p></p>

- On <https://default.api.witty.works/form>, I write "liebe Kollegen".

- I choose as alternative "Kollegschaft"

- It get's highlighted, since the word is not recognized in the language tool (see attached video)

<p></p>

## ACC. Criteria

The word "Kollegschaft" is recognized by our algorithm

**Comment by lsmith77** [comment]
Link to feature: https://wittyworks.productboard.com/feature-board/planning/features/11026243

**Comment by lsmith77** [comment]
probably the most feasible solution is a script looks which of our alternatives is considered a spelling mistake by LT and then generates a dictionary file we load into our LT instance.

**Comment by lsmith77** [comment]
https://stackoverflow.com/questions/37412145/in-languagetool-how-do-you-create-a-dictionary-and-use-it-for-spell-checking

**Comment by Szarad** [comment]
So the approach I take is to put all  alternatives to ignore.txt file. 
Examples as Kollegschaft works without problem.
However cases with forward slash are causing runtime error:
`Caused by: java.lang.IllegalArgumentException: Unknown suffix: -in in line: Abdichter/-in`
which is a problem because Abdichter/-in also show as spelling mistake
I need to look more on that and either add it to spelling file or generate new dictionary in the end.

**Comment by lsmith77** [comment]
another approach could be to customize which rules we have active.

you can check the rule that is triggered here:
https://languagetool.org/http-api/swagger-ui/#!/default/post_check

and then disable it here:
https://github.com/witty-works/nlp_api/blob/dev/languagetool/server.properties#L22

**Comment by lsmith77** [comment]
I had some exchanges with LT about this topic and it seems like they have added a rule for `:` .. we could also explore expanding this further:
https://github.com/languagetool-org/languagetool/commit/2474aacaeffd476e8dea016d4cb15c4db6507e75
