### ISSUE TITLE
reduce rate for health probes

### ISSUE THREAD

**Issue by lsmith77** [witty-works/nlp_api#336]

**Comment by lsmith77** [comment]
@Szarad I just checked again on prod and I still see a lot of requests from "Edge Health Probe"

**Comment by Szarad** [comment]
As we discussed, normal frequency is around 100-200 req per minute [1] , which is putting too much load on server. It is caused by high number of Front Door POPs (point of presences).
However, maybe before temporary disabling, I will put the maximum value for interval (255) and see how much it helps.

[1] https://docs.microsoft.com/en-us/azure/frontdoor/front-door-backend-pool 

I find some resource regarding health probe frequency, e.g.:
https://social.msdn.microsoft.com/Forums/en-US/75cfb536-71f6-4c88-ac80-ec693f3e6229/azure-front-door-healthcheck-frequency?forum=WAVirtualMachinesVirtualNetwork

**Comment by lsmith77** [comment]
ok

BTW we have not really measured the impact of the load generated. we just assume its a bit much.

**Comment by lsmith77** [comment]
did you do this for only LT (it seems like the health probe requests are going slower there) or for all our sites? because on the NLP API they still seem to be coming in very fast.

**Comment by Szarad** [comment]
At first I did it only for LT, but yesterday I changed it for all sites (to maximum interval value of 255). Now I changed also request endpoint for NLP API, before it was `/form` and health probe can't handle the redirection. I changed it to `\categories`, change should be visible in the server soon (in an hour maybe, when deployment will be done). The frequency of request is already in place.

**Comment by lsmith77** [comment]
ok .. seems to do the trick
